# Generated by Django 3.2.6 on 2021-08-20 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='company',
            name='group',
            field=models.CharField(choices=[('OU', 'Ours'), ('LO', 'Logistics'), ('IN', 'Insurance'), ('VE', 'Vendors'), ('GN', 'General')], default='GN', max_length=2),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
    ]
