# Generated by Django 3.2.6 on 2021-08-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210813_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
