# Generated by Django 3.2.6 on 2021-08-14 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_link_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
                ('comments', models.TextField()),
                ('address', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('value', models.CharField(max_length=48)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.passwordaccount')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.AddField(
            model_name='passwordaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.passwordgroup'),
        ),
    ]
