# Generated by Django 3.2.6 on 2021-08-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210815_0946'),
        ('contacts', '0009_auto_20210813_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='driver',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
    ]
