# Generated by Django 3.2.6 on 2021-08-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210815_0946'),
        ('contacts', '0010_auto_20210815_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordaccount',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='passwordgroup',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
    ]
