# Generated by Django 3.2.6 on 2021-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20210815_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='group',
            field=models.CharField(blank=True, choices=[('OU', 'Ours'), ('LO', 'Logistics'), ('IN', 'Insurance'), ('VE', 'Vendors'), ('GN', 'General')], default='GN', max_length=2),
        ),
    ]
