# Generated by Django 3.2.6 on 2021-08-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0026_auto_20210817_1416'),
        ('contacts', '0012_company_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordgroup',
            name='address',
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('group', 'OU'), ('group', 'LO'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.company'),
        ),
        migrations.AddField(
            model_name='passwordgroup',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.trailer'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.truck'),
        ),
    ]
