# Generated by Django 3.2.6 on 2021-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcolshow',
            name='list_name',
            field=models.CharField(max_length=18),
        ),
        migrations.AddConstraint(
            model_name='listcolshow',
            constraint=models.UniqueConstraint(fields=('profile', 'list_name', 'field_name'), name='unique_listcolshow'),
        ),
    ]
