# Generated by Django 3.2.6 on 2021-08-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcolshow',
            name='field_name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='listcolshow',
            name='list_name',
            field=models.CharField(max_length=24),
        ),
    ]
