# Generated by Django 3.2.6 on 2021-08-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencelist',
            name='trucks_font',
        ),
        migrations.AddField(
            model_name='preferencelist',
            name='font_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=36),
        ),
    ]
