# Generated by Django 3.2.6 on 2021-08-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210818_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('N', 'None'), ('R', 'Read'), ('W', 'Write'), ('A', 'Admin')], default='N', max_length=1),
        ),
    ]
