# Generated by Django 3.2.6 on 2021-08-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210821_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcolshow',
            options={'ordering': ['profile', '-list_name', 'order'], 'verbose_name_plural': 'ListColShows'},
        ),
        migrations.AddField(
            model_name='listcolshow',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
