# Generated by Django 3.2.6 on 2021-09-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_punchcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchcard',
            name='lunch_in_distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punchcard',
            name='lunch_out_distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punchcard',
            name='punch_in_distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punchcard',
            name='punch_out_distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
