# Generated by Django 3.2.6 on 2021-08-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210814_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcolshow',
            options={'verbose_name_plural': 'ListColShows'},
        ),
        migrations.AddField(
            model_name='listcolshow',
            name='verbose_name',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
    ]
