# Generated by Django 3.2.6 on 2021-08-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210823_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencelist',
            name='labor_rate',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
