# Generated by Django 3.2.6 on 2021-08-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210814_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcolshow',
            name='field_verbose_name',
        ),
        migrations.RemoveField(
            model_name='listcolshow',
            name='list_verbose_name',
        ),
    ]
