# Generated by Django 3.2.6 on 2021-08-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_preferencelist_labor_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='db_name',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
