# Generated by Django 3.2.6 on 2021-09-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210903_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_latitude',
            field=models.FloatField(default=42.0203018),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_longitude',
            field=models.FloatField(default=-88.318316),
        ),
    ]
