# Generated by Django 3.2.6 on 2021-08-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='db_name',
            field=models.CharField(default='guest', max_length=12),
        ),
    ]
