# Generated by Django 3.2.6 on 2021-09-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210903_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punchcard',
            options={'ordering': ['punch_in']},
        ),
    ]
