# Generated by Django 3.2.6 on 2021-09-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_inspection_options'),
        ('users', '0006_alter_punchcard_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchcard',
            name='profile',
        ),
        migrations.AddField(
            model_name='punchcard',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.mechanic'),
        ),
    ]
