# Generated by Django 3.2.6 on 2021-08-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcolshow',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='listcolshow',
            constraint=models.UniqueConstraint(fields=('profile', 'list_name', 'order'), name='unique_listcolshow_order'),
        ),
    ]
