# Generated by Django 3.2.6 on 2021-08-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210814_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcolshow',
            options={'ordering': ['profile', '-list_name', 'order'], 'verbose_name_plural': 'ListColShows'},
        ),
        migrations.RemoveConstraint(
            model_name='listcolshow',
            name='unique_listcolshow_order',
        ),
    ]
