# Generated by Django 3.2.6 on 2021-08-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210826_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parts_surcharge',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=3),
        ),
    ]
