# Generated by Django 3.2.6 on 2021-08-31 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_alter_company_group'),
        ('users', '0008_profile_parts_surcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_header',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'OU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.company'),
        ),
    ]
