# Generated by Django 3.2.6 on 2021-08-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210814_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcolshow',
            name='db_field_name',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
    ]
