# Generated by Django 3.2.8 on 2022-01-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210918_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punchcard',
            options={'ordering': ['-punch_in']},
        ),
    ]
