# Generated by Django 3.2.6 on 2021-08-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_listcolshow_db_field_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcolshow',
            options={'ordering': ['profile', '-list_name'], 'verbose_name_plural': 'ListColShows'},
        ),
        migrations.RemoveField(
            model_name='listcolshow',
            name='db_field_name',
        ),
        migrations.RemoveField(
            model_name='listcolshow',
            name='order',
        ),
    ]
