# Generated by Django 3.2.6 on 2021-09-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_shop_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=3),
        ),
    ]
