# Generated by Django 3.2.8 on 2022-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_punchcard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchcard',
            name='ot',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
