# Generated by Django 3.2.6 on 2022-08-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_punchcard_ot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
