# Generated by Django 3.2.6 on 2022-08-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_accountvar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='home_latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='home_longitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='labor_rate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parts_surcharge',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shop_header',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tax',
        ),
    ]
