# Generated by Django 3.2.6 on 2021-08-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_preferancelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreferanceList',
            new_name='PreferenceList',
        ),
    ]
