from django.urls import path

from .views import (
    OrderListView,
    OrderView,
    OrderPrintView,
    budget_invoice,
    JobFormSetView,
    JobPartListView,
    PartFormSetView,
    PurchaseListView,
    PurchaseView,
    budget_purchase,
    BalanceFormSetView,
    InspectionListView,
    InspectionView,
)

app_name = "shop"

urlpatterns = [
    path('orders/', OrderListView.as_view(),
         name='orders'),
    path('orders/create/', OrderView.as_view(is_create=True),
         name='create_order'),
    path('orders/<int:pk>/', OrderView.as_view(),
         name='order'),
    path('orders/<int:pk>/print', OrderPrintView.as_view(),
         name='order_print'),
    path('orders/<int:pk>/budget', budget_invoice,
         name='order_budget'),
    path('jobs/', JobFormSetView.as_view(),
         name='jobs'),
    path('jobs/<int:pk>/parts/', JobPartListView.as_view(),
         name='job_parts'),
    path('parts/', PartFormSetView.as_view(),
         name='parts'),
    path('purchases/', PurchaseListView.as_view(),
         name='purchases'),
    path('purchases/create/', PurchaseView.as_view(is_create=True),
         name='create_purchase'),
    path('purchases/<int:pk>/', PurchaseView.as_view(),
         name='purchase'),
    path('purchases/<int:pk>/budget', budget_purchase,
         name='purchase_budget'),
    path('accounting/', BalanceFormSetView.as_view(),
         name='balance'),
    path('inspections/', InspectionListView.as_view(),
         name='inspections'),
    path('inspections/create/', InspectionView.as_view(is_create=True),
         name='create_inspection'),
    path('inspections/<int:pk>/', InspectionView.as_view(),
         name='inspection'),
]
