from django.urls import path

from .views import (
    OrderListView,
    OrderView,
    OrderPrintView,
    budget_invoice,
    JobFormSetView,
    JobPartListView,
    JobPartTypeListView,
    PartFormSetView,
    PartDetailView,
    PurchaseListView,
    PurchaseView,
    budget_purchase,
    BalanceFormSetView,
    PartPlaceFormSetView,
    assign_to_all,
    ShelfListView,)

app_name = "shop"

urlpatterns = [
    path('orders/', OrderListView.as_view(),
         name='orders'),
    path('orders/create/', OrderView.as_view(is_create=True),
         name='create_order'),
    path('orders/<int:pk>/', OrderView.as_view(),
         name='order'),
    path('orders/<int:pk>/print', OrderPrintView.as_view(),
         name='order_print'),
    path('orders/<int:pk>/budget', budget_invoice,
         name='order_budget'),
    path('jobs/', JobFormSetView.as_view(),
         name='jobs'),
    path('jobs/<int:pk>/parts/', JobPartListView.as_view(),
         name='job_parts'),
    path('jobs/<int:pk>/part_types/', JobPartTypeListView.as_view(),
         name='job_part_types'),
    path('parts/', PartFormSetView.as_view(),
         name='parts'),
    path('parts/<int:pk>/', PartDetailView.as_view(),
         name='part'),
    path('purchases/', PurchaseListView.as_view(),
         name='purchases'),
    path('purchases/create/', PurchaseView.as_view(is_create=True),
         name='create_purchase'),
    path('purchases/<int:pk>/', PurchaseView.as_view(),
         name='purchase'),
    path('purchases/<int:pk>/budget', budget_purchase,
         name='purchase_budget'),
    path('accounting/', BalanceFormSetView.as_view(),
         name='balance'),
    path('assign/<int:pk>/<slug:unit>/', PartPlaceFormSetView.as_view(),
         name='assign_part'),
    path('assign_to_all/<int:pk>/<slug:unit>/', assign_to_all,
         name='assign_to_all'),
    path('shelves/', ShelfListView.as_view(),
         name='shelves'),
]
