# Generated by Django 3.2.6 on 2021-08-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='lic_plate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='make',
            field=models.CharField(blank=True, choices=[('VL', 'Volvo'), ('FL', 'Freighliner'), ('KW', 'Kenworth'), ('PB', 'Peterbilt')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='model',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
