# Generated by Django 3.2.6 on 2021-08-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invent', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='truck',
            name='insurer',
            field=models.ForeignKey(blank=True, db_column='insurer_id', limit_choices_to={'group': 'IN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_trailers', to='invent.company'),
        ),
        migrations.AddField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', limit_choices_to=models.Q(('group', 'OU'), ('group', 'LO'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_trucks', to='invent.company'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.company'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='insurer',
            field=models.ForeignKey(blank=True, db_column='insurer_id', limit_choices_to={'group': 'IN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_trucks', to='invent.company'),
        ),
        migrations.AddField(
            model_name='passwordrecord',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.passwordaccount'),
        ),
        migrations.AddField(
            model_name='passwordgroup',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='passwordaccount',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='passwordaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.passwordgroup'),
        ),
        migrations.AddField(
            model_name='driver',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('group', 'OU'), ('group', 'LO'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.company'),
        ),
        migrations.AddField(
            model_name='driver',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.trailer'),
        ),
        migrations.AddField(
            model_name='driver',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.truck'),
        ),
        migrations.AddField(
            model_name='company',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddConstraint(
            model_name='truck',
            constraint=models.UniqueConstraint(fields=('account', 'vin'), name='unique_truck'),
        ),
        migrations.AddConstraint(
            model_name='trailer',
            constraint=models.UniqueConstraint(fields=('account', 'vin'), name='unique_trailer'),
        ),
        migrations.AddConstraint(
            model_name='passwordrecord',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='password_record'),
        ),
        migrations.AddConstraint(
            model_name='passwordgroup',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='password_group'),
        ),
        migrations.AddConstraint(
            model_name='passwordaccount',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='password_account'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('account', 'group', 'name'), name='unique_company'),
        ),
    ]
