# Generated by Django 3.2.6 on 2021-08-18 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_initial'),
        ('invent', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='truck',
            name='insurer',
            field=models.ForeignKey(blank=True, db_column='insurer_id', limit_choices_to={'group': 'IN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_trailers', to='contacts.company'),
        ),
        migrations.AddField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', limit_choices_to=models.Q(('group', 'OU'), ('group', 'LO'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_trucks', to='contacts.company'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.company'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='insurer',
            field=models.ForeignKey(blank=True, db_column='insurer_id', limit_choices_to={'group': 'IN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_trucks', to='contacts.company'),
        ),
    ]
