# Generated by Django 3.2.6 on 2021-09-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_alter_company_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='group',
            field=models.CharField(choices=[('OU', 'Ours'), ('LO', 'Owners'), ('IN', 'Insurance'), ('VE', 'Vendors'), ('CS', 'Customers')], max_length=2),
        ),
    ]
