# Generated by Django 3.2.6 on 2021-08-19 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
        ('invent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.company'),
        ),
    ]
