# Generated by Django 3.2.6 on 2021-08-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_auto_20210811_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='engine',
            field=models.CharField(blank=True, choices=[('CT', 'Caterpillar'), ('CM', 'Cummins'), ('DT', 'Detroit'), ('IN', 'International'), ('PC', 'Paccar'), ('VL', 'Volvo')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_model',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='ins_exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='reg_exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fleet_number',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='lic_plate',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(blank=True, choices=[('FL', 'Freighliner'), ('IN', 'International'), ('KW', 'Kenworth'), ('PB', 'Peterbilt'), ('VL', 'Volvo'), ('WS', 'Western Star')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
