# Generated by Django 3.2.6 on 2021-08-21 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
