# Generated by Django 3.2.6 on 2021-08-21 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_alter_trailer_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='end_date',
        ),
        migrations.AddField(
            model_name='driver',
            name='cdl',
            field=models.CharField(blank=True, max_length=20, verbose_name='CDL#'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cdl_exp_date',
            field=models.DateField(blank=True, null=True, verbose_name='CDL exp'),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='DOB'),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='driver',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_clearinghouse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_mvr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_exp_date',
            field=models.DateField(blank=True, null=True, verbose_name='Medical exp'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pre_empl_clearinghouse',
            field=models.BooleanField(default=False, verbose_name='Pre-empl Clearinghouse'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pre_empl_drugtest',
            field=models.BooleanField(default=False, verbose_name='DrugTest'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pre_empl_verification',
            field=models.BooleanField(default=False, verbose_name='PEV'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(regex='^(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}$')]),
        ),
        migrations.AddField(
            model_name='driver',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hire Date'),
        ),
        migrations.AddField(
            model_name='driver',
            name='term_date',
            field=models.DateField(blank=True, null=True, verbose_name='Term date'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2),
        ),
        migrations.AddField(
            model_name='trailer',
            name='term_date',
            field=models.DateField(blank=True, null=True, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_pm_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last PM'),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_pm_mls',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='odometer'),
        ),
        migrations.AddField(
            model_name='truck',
            name='term_date',
            field=models.DateField(blank=True, null=True, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='inspection',
            field=models.DateField(blank=True, null=True, verbose_name='Annual exp'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='registration',
            field=models.DateField(blank=True, null=True, verbose_name='Reg exp'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='inspection',
            field=models.DateField(blank=True, null=True, verbose_name='Annual exp'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='registration',
            field=models.DateField(blank=True, null=True, verbose_name='Reg exp'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start'),
        ),
    ]
