# Generated by Django 3.2.6 on 2021-08-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_auto_20210812_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
