# Generated by Django 3.2.6 on 2021-08-19 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_alter_trailer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='fleet_number',
            field=models.CharField(max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='license_plate',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='vin',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='VIN'),
        ),
    ]
