# Generated by Django 3.2.6 on 2021-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0004_auto_20210906_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
