# Generated by Django 3.2.6 on 2021-08-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0004_truck_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_number', models.CharField(max_length=5, null=True)),
                ('lic_plate', models.CharField(blank=True, max_length=7, null=True)),
                ('make', models.CharField(blank=True, choices=[('HY', 'Hyundai'), ('UT', 'Utility'), ('WB', 'Wabash')], max_length=2, null=True)),
                ('year_made', models.IntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='year_made',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
