# Generated by Django 3.2.6 on 2021-08-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0004_auto_20210819_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['fleet_number']},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['fleet_number']},
        ),
    ]
