# Generated by Django 3.2.6 on 2021-08-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0005_driver_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='company',
        ),
        migrations.AddField(
            model_name='trailer',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_trailers', to='invent.company'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='insurer',
            field=models.ForeignKey(blank=True, db_column='insurer', limit_choices_to={'group': 'IN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_trailers', to='invent.company'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='insurer',
            field=models.ForeignKey(blank=True, db_column='insurer', limit_choices_to={'group': 'IN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_trucks', to='invent.company'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', limit_choices_to=models.Q(('group', 'OU'), ('group', 'LO'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_trucks', to='invent.company'),
        ),
    ]
