# Generated by Django 3.2.6 on 2021-08-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0005_auto_20210812_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='fleet_number',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fleet_number',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
