# Generated by Django 3.2.6 on 2021-08-13 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_company_options'),
        ('invent', '0006_auto_20210812_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.company'),
        ),
        migrations.AddField(
            model_name='truck',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.company'),
        ),
    ]
