# Generated by Django 3.2.6 on 2021-08-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0006_auto_20210823_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
