# Generated by Django 3.2.6 on 2021-08-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_auto_20210823_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('V', 'Vacation'), ('T', 'Term')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Delivery'), ('I', 'Idle'), ('S', 'Shop'), ('T', 'Term')], default='I', max_length=2),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('D', 'Delivery'), ('I', 'Idle'), ('S', 'Shop'), ('T', 'Term')], default='I', max_length=2),
        ),
    ]
