# Generated by Django 3.2.6 on 2021-08-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_auto_20210812_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='fleet_number',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fleet_number',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
