# Generated by Django 3.2.6 on 2021-08-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0008_auto_20210812_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='is_active',
        ),
        migrations.AddField(
            model_name='trailer',
            name='status',
            field=models.CharField(blank=True, choices=[('HY', 'Hyundai'), ('UT', 'Utility'), ('WB', 'Wabash')], default='ID', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(blank=True, choices=[('FL', 'Freighliner'), ('IN', 'International'), ('KW', 'Kenworth'), ('PB', 'Peterbilt'), ('VL', 'Volvo'), ('WS', 'Western Star')], default='ID', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='lic_plate',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='License plate'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='year_made',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='ins_exp',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance expiration date'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='lic_plate',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='License plate'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='reg_exp',
            field=models.DateField(blank=True, null=True, verbose_name='Registraion expiration date'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year_made',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
