# Generated by Django 3.2.6 on 2021-08-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0008_auto_20210824_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('T', 'Term')], default='A', max_length=2),
        ),
    ]
