# Generated by Django 3.2.6 on 2021-10-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0008_auto_20210918_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='make',
            field=models.CharField(blank=True, choices=[('HY', 'Hyundai'), ('GD', 'Great Dane'), ('UT', 'Utility'), ('VN', 'Vanguard'), ('WB', 'Wabash')], max_length=2),
        ),
    ]
