# Generated by Django 3.2.6 on 2021-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_company_comments'),
        ('invent', '0009_auto_20210813_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='status',
            field=models.CharField(blank=True, choices=[('DL', 'On delivery'), ('ID', 'Idle'), ('SH', 'In the shop'), ('IA', 'Inactive')], default='ID', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(blank=True, choices=[('DL', 'On delivery'), ('ID', 'Idle'), ('SH', 'In the shop'), ('IA', 'Inactive')], default='ID', max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='trailer',
            unique_together={('fleet_number', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='truck',
            unique_together={('fleet_number', 'company')},
        ),
    ]
