# Generated by Django 3.2.8 on 2021-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0009_alter_trailer_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='make',
            field=models.CharField(blank=True, choices=[('HY', 'Hyundai'), ('GD', 'Great Dane'), ('ST', 'Strickland'), ('UT', 'Utility'), ('VN', 'Vanguard'), ('WB', 'Wabash')], max_length=2),
        ),
    ]
