# Generated by Django 3.2.6 on 2021-08-26 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0009_alter_driver_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_company',
        ),
        migrations.RemoveConstraint(
            model_name='passwordaccount',
            name='password_account',
        ),
        migrations.RemoveConstraint(
            model_name='passwordgroup',
            name='password_group',
        ),
        migrations.RemoveConstraint(
            model_name='passwordrecord',
            name='password_record',
        ),
        migrations.RemoveConstraint(
            model_name='trailer',
            name='unique_trailer',
        ),
        migrations.RemoveConstraint(
            model_name='truck',
            name='unique_truck',
        ),
        migrations.RemoveField(
            model_name='company',
            name='account',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='account',
        ),
        migrations.RemoveField(
            model_name='passwordaccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='passwordgroup',
            name='account',
        ),
        migrations.RemoveField(
            model_name='passwordrecord',
            name='account',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='account',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='account',
        ),
        migrations.AlterField(
            model_name='passwordaccount',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordgroup',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordrecord',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='VIN'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_company'),
        ),
    ]
