# Generated by Django 3.2.6 on 2021-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0010_auto_20210813_1118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='truck',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='truck',
            constraint=models.UniqueConstraint(fields=('fleet_number', 'company'), name='unique truck record'),
        ),
    ]
