# Generated by Django 3.2.6 on 2021-08-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0010_auto_20210826_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='company',
        ),
        migrations.AddField(
            model_name='driver',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('group', 'OU'), ('group', 'LO'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.company', verbose_name='Company'),
        ),
    ]
