# Generated by Django 3.2.6 on 2021-08-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0011_auto_20210813_1125'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='truck',
            name='unique truck record',
        ),
        migrations.AlterUniqueTogether(
            name='trailer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='truck',
            constraint=models.UniqueConstraint(fields=('fleet_number', 'company'), name='unique_truck'),
        ),
    ]
