# Generated by Django 3.2.6 on 2022-02-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0012_auto_20220219_1742'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trailer',
            name='unique_trailer_plate',
        ),
        migrations.RemoveConstraint(
            model_name='truck',
            name='unique_truck_plate',
        ),
    ]
