# Generated by Django 3.2.6 on 2021-08-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0012_auto_20210813_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='fleet_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fleet_number',
            field=models.IntegerField(null=True),
        ),
    ]
