# Generated by Django 3.2.6 on 2021-08-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0013_auto_20210813_1301'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trailer',
            constraint=models.UniqueConstraint(fields=('fleet_number', 'company'), name='unique_trailer'),
        ),
    ]
