# Generated by Django 3.2.6 on 2021-08-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0013_auto_20210830_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='group',
            field=models.CharField(choices=[('OU', 'Ours'), ('LO', 'Logistics'), ('IN', 'Insurance'), ('VE', 'Vendors'), ('CS', 'Customers')], default='GN', max_length=2),
        ),
    ]
