# Generated by Django 3.2.6 on 2021-08-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_trailer_unique_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='fleet_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='lic_plate',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='License plate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='make',
            field=models.CharField(blank=True, choices=[('HY', 'Hyundai'), ('UT', 'Utility'), ('WB', 'Wabash')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='status',
            field=models.CharField(blank=True, choices=[('DL', 'On delivery'), ('ID', 'Idle'), ('SH', 'In the shop'), ('IA', 'Inactive')], default='ID', max_length=2),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=17, verbose_name='VIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='year_made',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='engine',
            field=models.CharField(blank=True, choices=[('CT', 'Caterpillar'), ('CM', 'Cummins'), ('DT', 'Detroit'), ('IN', 'International'), ('PC', 'Paccar'), ('VL', 'Volvo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='engine_model',
            field=models.CharField(blank=True, default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='engine_number',
            field=models.CharField(blank=True, default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='fleet_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='lic_plate',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='License plate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(blank=True, choices=[('FL', 'Freighliner'), ('IN', 'International'), ('KW', 'Kenworth'), ('PB', 'Peterbilt'), ('VL', 'Volvo'), ('WS', 'Western Star')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(blank=True, default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(blank=True, choices=[('DL', 'On delivery'), ('ID', 'Idle'), ('SH', 'In the shop'), ('IA', 'Inactive')], default='ID', max_length=2),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=17, verbose_name='VIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='year_made',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
