# Generated by Django 3.2.6 on 2022-07-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_auto_20220406_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='kt_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', limit_choices_to=models.Q(('group', 'OU'), ('group', 'LO'), ('group', 'CS'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_trailers', to='invent.company'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', limit_choices_to=models.Q(('group', 'OU'), ('group', 'LO'), ('group', 'CS'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_trucks', to='invent.company'),
        ),
    ]
