# Generated by Django 3.2.6 on 2021-08-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0015_auto_20210813_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='ins_exp',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='reg_exp',
            field=models.DateField(blank=True, null=True, verbose_name='Registraion'),
        ),
    ]
