# Generated by Django 3.2.6 on 2022-08-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0015_auto_20220705_1710'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trailer',
            name='unique_trailer_plate',
        ),
        migrations.RemoveConstraint(
            model_name='truck',
            name='unique_truck_plate',
        ),
    ]
