# Generated by Django 3.2.6 on 2021-08-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0016_auto_20210814_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='lic_plate',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='year_made',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='engine_model',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='ins_exp',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='lic_plate',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='reg_exp',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='year_made',
        ),
        migrations.AddField(
            model_name='trailer',
            name='license_plate',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='trailer',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='insurance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='truck',
            name='registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='vin',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('DL', 'On delivery'), ('ID', 'Idle'), ('SH', 'In the shop'), ('IA', 'Inactive')], default='ID', max_length=2),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
