# Generated by Django 3.2.6 on 2021-08-15 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20210815_0955'),
        ('invent', '0018_auto_20210815_0946'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='truck',
            name='unique_truck',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='model',
        ),
        migrations.AlterField(
            model_name='truck',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.company'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='engine_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fleet_number',
            field=models.CharField(max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AddConstraint(
            model_name='truck',
            constraint=models.UniqueConstraint(fields=('account', 'vin'), name='unique_truck'),
        ),
    ]
