# Generated by Django 3.2.6 on 2021-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0023_auto_20210816_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN'),
        ),
    ]
