# Generated by Django 3.2.6 on 2021-08-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0025_auto_20210817_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='gps',
            field=models.BooleanField(default=False, verbose_name='GPS'),
        ),
        migrations.AddField(
            model_name='truck',
            name='ky_permit',
            field=models.BooleanField(default=False, verbose_name='KY'),
        ),
        migrations.AddField(
            model_name='truck',
            name='nm_permit',
            field=models.BooleanField(default=False, verbose_name='NM'),
        ),
        migrations.AddField(
            model_name='truck',
            name='or_permit',
            field=models.BooleanField(default=False, verbose_name='OR'),
        ),
    ]
