# Generated by Django 3.2.6 on 2021-08-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20210817_1851'),
        ('invent', '0026_auto_20210817_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Terminated'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='gps',
            field=models.BooleanField(default=False, verbose_name='GPS'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='insurance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='insurer',
            field=models.ForeignKey(blank=True, db_column='insurer_id', limit_choices_to={'group': 'IN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_trucks', to='contacts.company'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Started'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='license_plate',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='status',
            field=models.CharField(blank=True, choices=[('DL', 'Trip'), ('ID', 'Idle'), ('SH', 'Shop'), ('IA', 'Term')], default='ID', max_length=2),
        ),
        migrations.AlterField(
            model_name='truck',
            name='insurer',
            field=models.ForeignKey(blank=True, db_column='insurer_id', limit_choices_to={'group': 'IN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_trailers', to='contacts.company'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', limit_choices_to=models.Q(('group', 'OU'), ('group', 'LO'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_trucks', to='contacts.company'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('DL', 'Trip'), ('ID', 'Idle'), ('SH', 'Shop'), ('IA', 'Term')], default='ID', max_length=2),
        ),
    ]
