# Generated by Django 3.2.6 on 2021-09-01 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invent', '0002_alter_company_group'),
        ('shop', '0004_alter_inspection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(default=datetime.date(2021, 9, 1))),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.truck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrailerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(default=datetime.date(2021, 9, 1))),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.trailer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(default=datetime.date(2021, 9, 1))),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(default=datetime.date(2021, 9, 1))),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inspection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
