# Generated by Django 3.2.6 on 2021-09-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_alter_company_group'),
        ('docs', '0002_auto_20210901_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('category', models.CharField(choices=[('IN', 'Insurance'), ('RG', 'Registration'), ('DI', 'DOT Inspection'), ('BL', 'Bills'), ('GN', 'General')], default='GN', max_length=2)),
                ('description', models.CharField(max_length=50)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.truck')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
