# Generated by Django 3.2.6 on 2021-09-06 15:47

from django.db import migrations, models
import docs.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_companydocument_driverdocument_trailerdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='origin',
        ),
        migrations.AlterField(
            model_name='trailerimage',
            name='image',
            field=models.ImageField(upload_to=docs.models.img_upload_directory),
        ),
        migrations.AlterField(
            model_name='truckimage',
            name='image',
            field=models.ImageField(upload_to=docs.models.img_upload_directory),
        ),
        migrations.DeleteModel(
            name='InspectionImage',
        ),
        migrations.DeleteModel(
            name='OrderImage',
        ),
    ]
