# Generated by Django 3.2.6 on 2022-02-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20211027_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverDocument',
        ),
    ]
