# Generated by Django 3.2.8 on 2022-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_delete_driverdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocument',
            name='category',
            field=models.CharField(choices=[('IN', 'Insurance'), ('RG', 'Registration'), ('DI', 'Inspection'), ('BL', 'Bills'), ('GN', 'General')], default='GN', max_length=2),
        ),
        migrations.AlterField(
            model_name='trailerdocument',
            name='category',
            field=models.CharField(choices=[('IN', 'Insurance'), ('RG', 'Registration'), ('DI', 'Inspection'), ('BL', 'Bills'), ('GN', 'General')], default='GN', max_length=2),
        ),
        migrations.AlterField(
            model_name='truckdocument',
            name='category',
            field=models.CharField(choices=[('IN', 'Insurance'), ('RG', 'Registration'), ('DI', 'Inspection'), ('BL', 'Bills'), ('GN', 'General')], default='GN', max_length=2),
        ),
    ]
