# Generated by Django 3.2.6 on 2021-08-27 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invent', '0010_auto_20210826_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpPartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('stock_unit', models.CharField(default=True, max_length=10)),
                ('trailers', models.ManyToManyField(to='invent.Trailer')),
                ('trucks', models.ManyToManyField(to='invent.Truck')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='PartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vendor', models.ForeignKey(limit_choices_to={'group': 'VE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StdOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pm', models.BooleanField(default=False)),
                ('parts', models.ManyToManyField(to='shop.OpPartItem')),
            ],
        ),
        migrations.CreateModel(
            name='StdOpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('stdop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.stdop')),
            ],
        ),
        migrations.CreateModel(
            name='PartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amount', models.PositiveSmallIntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.part')),
                ('partorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.partorder')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('mechanic', models.CharField(blank=True, choices=[('VP', 'Vadim')], max_length=2, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('stdopitems', models.ManyToManyField(to='shop.StdOpItem')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.trailer')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.truck')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='oppartitem',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.part'),
        ),
    ]
