# Generated by Django 3.2.6 on 2021-08-29 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invent', '0010_auto_20210826_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('man_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('mechanic', models.CharField(blank=True, choices=[('VP', 'Vadim')], default='VP', max_length=2, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('closed', models.DateField(blank=True, null=True)),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.trailer')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.truck')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('stock_unit', models.CharField(blank=True, max_length=10)),
                ('trailers', models.ManyToManyField(blank=True, to='invent.Trailer')),
                ('trucks', models.ManyToManyField(blank=True, to='invent.Truck')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vendor', models.ForeignKey(limit_choices_to={'group': 'VE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amount', models.PositiveSmallIntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.part')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.part')),
            ],
        ),
        migrations.CreateModel(
            name='OrderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_items', to='shop.job')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='parts',
            field=models.ManyToManyField(blank=True, to='shop.Part'),
        ),
    ]
