# Generated by Django 3.2.6 on 2021-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderjob',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
