# Generated by Django 3.2.6 on 2021-08-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_closed',
            new_name='closed',
        ),
    ]
