# Generated by Django 3.2.6 on 2021-08-27 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_date_closed_order_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_opened',
        ),
        migrations.AddField(
            model_name='order',
            name='opened',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mechanic',
            field=models.CharField(blank=True, choices=[('VP', 'Vadim')], default='VP', max_length=2, null=True),
        ),
    ]
