# Generated by Django 3.2.6 on 2021-08-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderjob_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderjob',
            name='man_hours',
        ),
    ]
