# Generated by Django 3.2.6 on 2021-09-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210901_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-id']},
        ),
    ]
