# Generated by Django 3.2.6 on 2021-08-31 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_alter_company_group'),
        ('shop', '0004_auto_20210831_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'CS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.company'),
        ),
    ]
