# Generated by Django 3.2.6 on 2021-09-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_ordertime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanic',
            options={},
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
