# Generated by Django 3.2.6 on 2021-09-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210905_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertime',
            name='stop',
        ),
        migrations.AddField(
            model_name='ordertime',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='ordertime',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
