# Generated by Django 3.2.6 on 2021-09-01 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210901_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('I', '+Invoice'), ('B', '-Building'), ('S', '-Salaries'), ('T', '-Tools'), ('S', '-Services'), ('P', '-Parts')], max_length=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comments', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
