# Generated by Django 3.2.6 on 2021-10-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_ordertime_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='category',
            field=models.CharField(choices=[('I', '+Invoice'), ('R', '+Refund'), ('B', '-Building'), ('S', '-Salaries'), ('T', '-Tools'), ('S', '-Services'), ('P', '-Parts'), ('E', '-Shop Supplies')], max_length=2),
        ),
    ]
