# Generated by Django 3.2.8 on 2021-11-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211027_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertime',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.mechanic'),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
