# Generated by Django 3.2.8 on 2021-12-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_ordertime_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='track',
            field=models.BooleanField(default=False),
        ),
    ]
