# Generated by Django 3.2.8 on 2022-01-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_part_track'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('part_number', 'name'), name='unique_part'),
        ),
    ]
