# Generated by Django 3.2.8 on 2022-02-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_part_unique_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='track_stock',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.ManyToManyField(blank=True, to='shop.PartType'),
        ),
    ]
