# Generated by Django 3.2.8 on 2022-02-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220218_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='axle',
            field=models.CharField(blank=True, choices=[('S', 'STR'), ('D', 'DRV'), ('A', 'ADD'), ('T', 'TRL')], max_length=1),
        ),
        migrations.AddField(
            model_name='parttype',
            name='side',
            field=models.CharField(blank=True, choices=[('L', 'L/S'), ('R', 'R/S')], max_length=1),
        ),
    ]
