# Generated by Django 3.2.6 on 2022-02-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_part_price'),
        ('shop', '0015_auto_20220218_0934'),
    ]

    operations = [
    ]
