# Generated by Django 3.2.6 on 2022-02-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0012_auto_20220219_1742'),
        ('shop', '0016_merge_0010_alter_part_price_0015_auto_20220218_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parttype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='parttype',
            name='axle',
        ),
        migrations.RemoveField(
            model_name='parttype',
            name='side',
        ),
        migrations.CreateModel(
            name='PartPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axle_str_left', models.BooleanField()),
                ('axle_str_right', models.BooleanField()),
                ('axle_drv_left', models.BooleanField()),
                ('axle_drv_right', models.BooleanField()),
                ('axle_add_leftt', models.BooleanField()),
                ('axle_add_right', models.BooleanField()),
                ('axle_trl_left', models.BooleanField()),
                ('axle_trl_right', models.BooleanField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.part')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.trailer')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.truck')),
            ],
        ),
    ]
