# Generated by Django 3.2.6 on 2022-02-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0013_auto_20220219_1745'),
        ('shop', '0018_auto_20220219_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partplace',
            name='trailer',
            field=models.ManyToManyField(blank=True, to='invent.Trailer'),
        ),
        migrations.AlterField(
            model_name='partplace',
            name='truck',
            field=models.ManyToManyField(blank=True, to='invent.Truck'),
        ),
    ]
