# Generated by Django 3.2.6 on 2022-02-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0013_auto_20220219_1745'),
        ('shop', '0019_auto_20220219_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partplace',
            name='trailer',
        ),
        migrations.AddField(
            model_name='partplace',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.trailer'),
        ),
        migrations.RemoveField(
            model_name='partplace',
            name='truck',
        ),
        migrations.AddField(
            model_name='partplace',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.truck'),
        ),
    ]
