# Generated by Django 3.2.6 on 2022-02-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220219_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partplace',
            old_name='axle_add_leftt',
            new_name='axle_add',
        ),
        migrations.RenameField(
            model_name='partplace',
            old_name='axle_add_right',
            new_name='axle_drv',
        ),
        migrations.RenameField(
            model_name='partplace',
            old_name='axle_drv_left',
            new_name='axle_str',
        ),
        migrations.RenameField(
            model_name='partplace',
            old_name='axle_drv_right',
            new_name='axle_trl',
        ),
        migrations.RenameField(
            model_name='partplace',
            old_name='axle_str_left',
            new_name='side_left',
        ),
        migrations.RenameField(
            model_name='partplace',
            old_name='axle_str_right',
            new_name='side_right',
        ),
        migrations.RemoveField(
            model_name='partplace',
            name='axle_trl_left',
        ),
        migrations.RemoveField(
            model_name='partplace',
            name='axle_trl_right',
        ),
    ]
