# Generated by Django 3.2.6 on 2022-02-20 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20220219_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_type',
        ),
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.parttype'),
        ),
    ]
