# Generated by Django 3.2.8 on 2022-02-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20220220_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='replaces',
            field=models.ManyToManyField(blank=True, to='shop.Part'),
        ),
    ]
