# Generated by Django 3.2.8 on 2022-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20220301_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='re_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
