# Generated by Django 3.2.8 on 2022-03-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_mechanic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
