# Generated by Django 3.2.8 on 2022-04-11 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_mechanic_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='vacation_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
