# Generated by Django 3.2.6 on 2022-08-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_balance_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.ManyToManyField(blank=True, to='shop.PartType')),
            ],
        ),
        migrations.AddField(
            model_name='shelf',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shelfgroup'),
        ),
    ]
