# Generated by Django 3.2.6 on 2022-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20220804_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfgroup',
            options={'ordering': ['order_number']},
        ),
        migrations.AddField(
            model_name='shelfgroup',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
