# Generated by Django 3.2.6 on 2022-08-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20220805_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.part')),
                ('purchase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.purchase')),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CoreReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField()),
                ('receipt', models.CharField(blank=True, max_length=20)),
                ('core', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.core')),
            ],
        ),
    ]
