# Generated by Django 3.2.6 on 2022-08-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20220816_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.purchaseitem'),
        ),
    ]
