# Generated by Django 3.2.6 on 2022-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_core_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='core',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
